# Build stage#usar Go 1.26 garante compatibilidade
FROM golang:1.24 AS builder   

# Instala ferramentas essenciais
RUN apt-get update && apt-get install -y git make

# Instala xk6
RUN go install go.k6.io/xk6/cmd/xk6@latest

# Cria diretório /k6 para o binário custom
RUN mkdir -p /k6

# Build do k6 custom com output InfluxDB
RUN xk6 build --with github.com/grafana/xk6-output-influxdb@latest --output /k6/k6_custom

# Stage final
FROM debian:bookworm-slim

# Copia binário customizado
COPY --from=builder /k6/k6_custom /k6/k6_custom

# Cria diretório para scripts
RUN mkdir -p /scripts
WORKDIR /scripts

ENTRYPOINT ["/k6/k6_custom"]
