version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: k6
      DOCKER_INFLUXDB_INIT_BUCKET: k6
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mysecret-token-123
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:10.0.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

  k6:
    build:
      context: ./k6-custom
      dockerfile: Dockerfile.k6
    container_name: k6
    volumes:
      - ./k6:/scripts
    depends_on:
      - influxdb
    entrypoint:
      - "/k6/k6_custom"
      - "run"
      - "/scripts/script.js"
      - "--out"
      - "influxdb=http://influxdb:8086"
      - "--out-org=k6"
      - "--out-bucket=k6"
      - "--out-token=mysecret-token-123"

volumes:
  influxdb_data:
  grafana_data:
