name: Performance Tests

on:
  push:
    branches:
      - '**'  # qualquer branch
  pull_request:
    branches:
      - '**'

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checa o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instala o k6 via Snap
      - name: Install k6
        run: |
          sudo snap install k6

      # 3. Dá permissão de execução ao script
      - name: Make test script executable
        run: chmod +x ./run_all.sh

      # 4. Executa todos os testes via script
      - name: Run all performance tests
        run: ./run_all.sh
