name: Performance Tests

# Executa o workflow em push para qualquer branch
on:
  push:
    branches:
      - '**'  # qualquer branch
  pull_request:  # opcional, também executa em PR
    branches:
      - '**'

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checa o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instala o k6
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
          sudo add-apt-repository ppa:k6io/k6
          sudo apt-get update
          sudo apt-get install -y k6

      # 3. Executa os testes de performance
      - name: Run k6 tests
        run: |
          k6 run ./k6-tests/performance/homepage_perf.js
          k6 run ./k6-tests/performance/category_perf.js
          k6 run ./k6-tests/performance/product_perf.js
          k6 run ./k6-tests/performance/cart_perf.js
          k6 run ./k6-tests/performance/checkout_perf.js
          k6 run ./k6-tests/performance/login_perf.js
